/**
 * SSS-141: Chaos Runner
 *
 * Entry point that:
 *   1. Imports and re-exports result arrays from all sub-fuzzers.
 *   2. Runs a standalone summary describe() block that verifies
 *      the aggregate count of adversarial scenarios meets the 50+ target.
 *   3. Writes docs/CHAOS-REPORT.md after all tests complete.
 *
 * Usage (stand-alone):
 *   npx ts-mocha -p tsconfig.json tests/chaos/chaosRunner.ts \
 *     tests/chaos/accountFuzzer.ts tests/chaos/amountFuzzer.ts \
 *     tests/chaos/sequenceFuzzer.ts tests/chaos/concurrencyFuzzer.ts
 *
 * The report is generated by the `after()` hook in the "ChaosRunner" suite.
 */

import * as fs from "fs";
import * as path from "path";
import { expect } from "chai";

// ── import result stores from sibling fuzzers ─────────────────────────────────
// These are populated at runtime when the sibling suites execute first.
import { accountFuzzerResults } from "./accountFuzzer";
import { amountFuzzerResults } from "./amountFuzzer";
import { sequenceFuzzerResults } from "./sequenceFuzzer";
import { concurrencyFuzzerResults } from "./concurrencyFuzzer";

// ── helpers ──────────────────────────────────────────────────────────────────

interface ScenarioResult {
  scenario: string;
  input: string;
  expectedError: string;
  passed: boolean;
  actualError?: string;
}

function tableRow(r: ScenarioResult): string {
  const status = r.passed ? "✅ PASS" : "❌ FAIL";
  const err = (r.actualError ?? "—").replace(/\|/g, "╎").slice(0, 80);
  return `| ${r.scenario} | ${r.input.slice(0, 40)} | ${r.expectedError.slice(0, 40)} | ${status} | ${err} |`;
}

function generateReport(allResults: ScenarioResult[]): string {
  const total = allResults.length;
  const passed = allResults.filter((r) => r.passed).length;
  const failed = total - passed;
  const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : "0.0";
  const now = new Date().toISOString();

  const accountRows = accountFuzzerResults.map(tableRow).join("\n");
  const amountRows = amountFuzzerResults.map(tableRow).join("\n");
  const sequenceRows = sequenceFuzzerResults.map(tableRow).join("\n");
  const concurrencyRows = concurrencyFuzzerResults.map(tableRow).join("\n");

  return `# SSS-141 Chaos/Fuzz Testing Report

> Auto-generated by \`tests/chaos/chaosRunner.ts\`  
> Generated: ${now}

## Summary

| Metric | Value |
|--------|-------|
| Total adversarial scenarios | ${total} |
| Passed (correctly rejected) | ${passed} |
| Failed (unexpected success or wrong error) | ${failed} |
| Pass rate | ${passRate}% |
| Minimum required | 50 |
| Requirement met | ${total >= 50 ? "✅ YES" : "❌ NO"} |

---

## Fuzzer Breakdown

| Fuzzer | Scenarios | Passed | Failed |
|--------|-----------|--------|--------|
| AccountFuzzer | ${accountFuzzerResults.length} | ${accountFuzzerResults.filter(r=>r.passed).length} | ${accountFuzzerResults.filter(r=>!r.passed).length} |
| AmountFuzzer | ${amountFuzzerResults.length} | ${amountFuzzerResults.filter(r=>r.passed).length} | ${amountFuzzerResults.filter(r=>!r.passed).length} |
| SequenceFuzzer | ${sequenceFuzzerResults.length} | ${sequenceFuzzerResults.filter(r=>r.passed).length} | ${sequenceFuzzerResults.filter(r=>!r.passed).length} |
| ConcurrencyFuzzer | ${concurrencyFuzzerResults.length} | ${concurrencyFuzzerResults.filter(r=>r.passed).length} | ${concurrencyFuzzerResults.filter(r=>!r.passed).length} |
| **Total** | **${total}** | **${passed}** | **${failed}** |

---

## AccountFuzzer — Adversarial Account Combinations (${accountFuzzerResults.length} scenarios)

Verifies all instructions reject wrong PDAs, swapped mints, and forged signers.

| Scenario | Input | Expected Error | Result | Actual Error |
|----------|-------|----------------|--------|--------------|
${accountRows || "| _(no results — run with localnet)_ | — | — | — | — |"}

---

## AmountFuzzer — Boundary & Extreme Amounts (${amountFuzzerResults.length} scenarios)

Verifies invariants hold at u64 extremes and boundary values.

| Scenario | Input | Expected Error | Result | Actual Error |
|----------|-------|----------------|--------|--------------|
${amountRows || "| _(no results — run with localnet)_ | — | — | — | — |"}

---

## SequenceFuzzer — Invalid Instruction Ordering (${sequenceFuzzerResults.length} scenarios)

Verifies state machine rejects out-of-order operations.

| Scenario | Input | Expected Error | Result | Actual Error |
|----------|-------|----------------|--------|--------------|
${sequenceRows || "| _(no results — run with localnet)_ | — | — | — | — |"}

---

## ConcurrencyFuzzer — Race Conditions & Double-Spend (${concurrencyFuzzerResults.length} scenarios)

Verifies no double-spend or state corruption under concurrent load.

| Scenario | Input | Expected Error | Result | Actual Error |
|----------|-------|----------------|--------|--------------|
${concurrencyRows || "| _(no results — run with localnet)_ | — | — | — | — |"}

---

## Adversarial Scenario Catalogue

The following is the full list of all ${total} adversarial scenarios tested in this run.  
Scenarios are numbered globally for traceability.

${allResults.map((r, i) => `${i + 1}. **${r.scenario}** — ${r.passed ? "✅" : "❌"} — expected: \`${r.expectedError}\``).join("\n")}

---

## Methodology

### AccountFuzzer
- Generates random keypairs and PDAs with wrong seeds
- Passes them as authority, mint, vault, and hook-program accounts
- Verifies Anchor constraint errors (ConstraintSeeds, AccountNotFound) or program errors (Unauthorized, InvalidMint, etc.)

### AmountFuzzer  
- Tests u64::MAX, u64::MAX-1, 0, and 1 for all mutable instructions
- Verifies ZeroAmount, MaxSupplyExceeded, overflow protection, and invariant guards

### SequenceFuzzer
- Inverts or skips prerequisite steps (e.g. burn before mint, liquidate before CDP open)
- Verifies the state machine enforces correct sequencing via error codes

### ConcurrencyFuzzer
- Submits identical or conflicting transactions as Promise.allSettled concurrently
- Verifies at-most-once semantics: at most 1 concurrent call succeeds
- Verifies idempotency: repeated identical calls produce deterministic outcomes

---

*Report generated by SSS-141 chaos testing suite. See \`tests/chaos/\` for source.*
`;
}

// ── describe block ────────────────────────────────────────────────────────────

describe("SSS-141 ChaosRunner — Aggregate Validation", () => {
  it("CR-01: at least 50 adversarial scenarios are registered", function () {
    // Results are populated by sibling suites that run before this describe
    const total =
      accountFuzzerResults.length +
      amountFuzzerResults.length +
      sequenceFuzzerResults.length +
      concurrencyFuzzerResults.length;
    expect(
      total,
      `Only ${total} scenarios registered — need >= 50. Run all fuzzer files together.`
    ).to.be.greaterThanOrEqual(50);
  });

  it("CR-02: pass rate is >= 90% across all fuzzers", function () {
    const allResults = [
      ...accountFuzzerResults,
      ...amountFuzzerResults,
      ...sequenceFuzzerResults,
      ...concurrencyFuzzerResults,
    ];
    if (allResults.length === 0) this.skip();
    const passed = allResults.filter((r) => r.passed).length;
    const rate = (passed / allResults.length) * 100;
    expect(
      rate,
      `Pass rate ${rate.toFixed(1)}% is below 90%. Review failures above.`
    ).to.be.greaterThanOrEqual(90);
  });

  after(async () => {
    const allResults: ScenarioResult[] = [
      ...accountFuzzerResults,
      ...amountFuzzerResults,
      ...sequenceFuzzerResults,
      ...concurrencyFuzzerResults,
    ];

    const report = generateReport(allResults);

    const repoRoot = path.resolve(__dirname, "..", "..");
    const docsDir = path.join(repoRoot, "docs");
    const reportPath = path.join(docsDir, "CHAOS-REPORT.md");

    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
    }
    fs.writeFileSync(reportPath, report, "utf8");

    console.log(`\n✅ CHAOS-REPORT.md written to ${reportPath}`);
    console.log(`   Total scenarios: ${allResults.length}`);
    console.log(`   Passed: ${allResults.filter((r) => r.passed).length}`);
  });
});
